services:
  frontend:
    container_name: dockerized-trybe-wallet
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5